config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 # get '/home', to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # CRUD task

  # CREATE

  get "/tasks/new", to: "tasks#new"

  post '/tasks', to: 'tasks#create'

  # READ

  # see all tasks

  get "/tasks", to: "tasks#index"

  # see one task

  get "/tasks/:id", to: 'tasks#show', as: "task"

  # UPDATE

  # form for editing a task

  get "/tasks/:id/edit", to: 'tasks#edit', as: "edit_task"

  # update a task

  patch "/tasks/:id", to: 'tasks#update'

  # DELETE

  delete 'tasks/:id', to: 'tasks#destroy'

  # resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
  Task.create(task_params)
  redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<% @tasks.each do |task| %>
  <div>
 <input type="checkbox" name="task"><%= link_to task.title, task_path(task)
 %>



  </div>

<% end %>

 <p><%= link_to " + Add a new task",  tasks_new_path %></p>

app/views/tasks/new.html.erb
<div class="form">

<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

</div>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<h2><%= @task.details %></h2>

<input type="checkbox" name="task"><%= @task.completed %>

<p> <%= link_to " ✏️Edit task",  edit_task_path %> </p>

<p><%= link_to "🗑 Delete", task_path(@task),
      method: :delete,
      data: { confirm: "Are you sure you wanna delete the task?" } %></p>


<p> <%= link_to " ◀︎ Back to tasks",  tasks_path %> </p>